name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zip libsqlite3-dev

      - name: Install gox
        run: go install github.com/authelia/gox@latest

      - name: Build binaries with gox
        run: |
          mkdir -p dist
          gox -osarch="linux/amd64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64" \
              -output "dist/wifi-attendance-logger_{{.OS}}_{{.Arch}}" \
              -ldflags "-X main.Version=${VERSION}"

      - name: Archive binaries with config.sample.yaml
        run: |
          mkdir -p upload
          
          # Copy config.sample.yaml
          cp config.sample.yaml dist/

          # Linux
          tar czvf upload/wifi-attendance-logger_linux_amd64.tgz -C dist wifi-attendance-logger_linux_amd64 config.sample.yaml

          # macOS amd64
          tar czvf upload/wifi-attendance-logger_macos_amd64.tgz -C dist wifi-attendance-logger_darwin_amd64 config.sample.yaml

          # macOS arm64
          tar czvf upload/wifi-attendance-logger_macos_arm64.tgz -C dist wifi-attendance-logger_darwin_arm64 config.sample.yaml

          # Windows amd64
          zip upload/wifi-attendance-logger_windows_amd64.zip dist/wifi-attendance-logger_windows_amd64.exe dist/config.sample.yaml

          # Windows arm64
          zip upload/wifi-attendance-logger_windows_arm64.zip dist/wifi-attendance-logger_windows_arm64.exe dist/config.sample.yaml

      - name: Generate SHA256 checksums
        run: |
          cd upload
          sha256sum *.{tgz,zip} > checksums.txt

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: upload/

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: upload/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
