name: Build, Test, and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux   GOARCH=amd64  go build -ldflags "-X main.Version=${VERSION}" -o dist/wifi-attendance-logger
          GOOS=linux   GOARCH=arm64  go build -ldflags "-X main.Version=${VERSION}" -o dist/wifi-attendance-logger
          GOOS=darwin  GOARCH=amd64  go build -ldflags "-X main.Version=${VERSION}" -o dist/wifi-attendance-logger
          GOOS=darwin  GOARCH=arm64  go build -ldflags "-X main.Version=${VERSION}" -o dist/wifi-attendance-logger
          GOOS=windows GOARCH=amd64  go build -ldflags "-X main.Version=${VERSION}" -o dist/wifi-attendance-logger.exe
          GOOS=windows GOARCH=arm64  go build -ldflags "-X main.Version=${VERSION}" -o dist/wifi-attendance-logger.exe

      - name: Archive binaries
        run: |
          mkdir -p upload
          cp config.sample.yaml dist/

          cd dist

          tar czvf ../upload/wifi-attendance-logger_linux_amd64_${VERSION}.tgz wifi-attendance-logger config.sample.yaml
          tar czvf ../upload/wifi-attendance-logger_linux_arm64_${VERSION}.tgz wifi-attendance-logger config.sample.yaml
          tar czvf ../upload/wifi-attendance-logger_macos_amd64_${VERSION}.tgz wifi-attendance-logger config.sample.yaml
          tar czvf ../upload/wifi-attendance-logger_macos_arm64_${VERSION}.tgz wifi-attendance-logger config.sample.yaml
          zip ../upload/wifi-attendance-logger_windows_amd64_${VERSION}.zip wifi-attendance-logger.exe config.sample.yaml
          zip ../upload/wifi-attendance-logger_windows_arm64_${VERSION}.zip wifi-attendance-logger.exe config.sample.yaml

      - name: Generate checksums
        run: |
          cd upload
          sha256sum *.{tgz,zip} > checksums.txt

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: upload/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: upload/

      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support wine

      - name: Test Linux amd64 binary
        run: |
          tar xzvf upload/wifi-attendance-logger_linux_amd64_${VERSION}.tgz
          chmod +x wifi-attendance-logger
          ./wifi-attendance-logger -version

      - name: Test Linux arm64 binary (qemu)
        run: |
          tar xzvf upload/wifi-attendance-logger_linux_arm64_${VERSION}.tgz
          chmod +x wifi-attendance-logger
          qemu-aarch64-static ./wifi-attendance-logger -version

      - name: Test Windows amd64 binary (wine)
        run: |
          unzip upload/wifi-attendance-logger_windows_amd64_${VERSION}.zip
          wine wifi-attendance-logger.exe -version

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: upload/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
